spring.application.name=home-service-application

spring.datasource.url=jdbc:postgresql://localhost:5432/home_service_db
spring.datasource.username=postgres
spring.datasource.password=Vishwas@2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true