--V1_init_schemas.sql
create SCHEMA IF not EXISTS auth;
create SCHEMA IF not EXISTS customer;
CREATE SCHEMA IF NOT EXISTS provider;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS booking;
CREATE SCHEMA IF NOT EXISTS admin;
CREATE SCHEMA IF NOT EXISTS ai;